window.QuizQuestionBank=(function(){function m(id,source,topic,topicEn,difficulty,mastery,question,questionEn,options,optionsEn,answer,explanation,explanationEn,extra){return Object.assign({id,source,topic,topicEn,difficulty,mastery,question,questionEn,options,optionsEn,answer,explanation,explanationEn},extra||{})}const topic=[],comprehensive=[],daily=[];function t(){topic.push(m.apply(null,arguments))}function c(id,difficulty,mastery,question,questionEn,options,optionsEn,answer,explanation,explanationEn){comprehensive.push(m(id,"comprehensive","综合题库","Mixed Bank",difficulty,mastery,question,questionEn,options,optionsEn,answer,explanation,explanationEn))}function d(id,topicZh,topicEn,difficulty,mastery,labelZh,labelEn,question,questionEn,options,optionsEn,answer,explanation,explanationEn){daily.push(m(id,"daily",topicZh,topicEn,difficulty,mastery,question,questionEn,options,optionsEn,answer,explanation,explanationEn,{difficultyLabel:labelZh,difficultyLabelEn:labelEn}))}
[2,3,4,5,6,7,8,9,10,11,12,13,14,15].forEach((r,i)=>t("topic-rd-"+String(i+1).padStart(3,"0"),"topic","圆的基本性质","Circle Basics",2+i%2,3+i%2,`已知某圆的半径为 ${r} cm，则它的直径是（ ）`,`If a circle has radius ${r} cm, its diameter is?`,[`${r} cm`,`${r*2} cm`,`${r*3} cm`,`${r*r} cm`],[`${r} cm`,`${r*2} cm`,`${r*3} cm`,`${r*r} cm`],1,`直径等于半径的两倍，所以结果是 ${r*2} cm。`,`The diameter is twice the radius, so the answer is ${r*2} cm.`));
[6,8,10,12,14,16,18,20,22,24,26,28,30,32].forEach((x,i)=>t("topic-dr-"+String(i+1).padStart(3,"0"),"topic","圆的基本性质","Circle Basics",2+(i%3===0),3,`某圆的直径为 ${x} cm，则它的半径是（ ）`,`A circle has diameter ${x} cm. Its radius is?`,[`${x/4} cm`,`${x/2} cm`,`${x} cm`,`${x*2} cm`],[`${x/4} cm`,`${x/2} cm`,`${x} cm`,`${x*2} cm`],1,`半径等于直径的一半，所以答案是 ${x/2} cm。`,`The radius is half the diameter, so the answer is ${x/2} cm.`));
[40,60,80,90,100,110,120,130,140,150,160,170].forEach((a,i)=>t("topic-ci-"+String(i+1).padStart(3,"0"),"topic","圆心角与圆周角","Central and Inscribed Angles",3+(i%3===0),2+i%3,`若某圆心角为 ${a}°，则同弧所对圆周角是（ ）`,`If a central angle is ${a}°, the inscribed angle on the same arc is?`,[`${a/4}°`,`${a/2}°`,`${a}°`,`${a*2}°`],[`${a/4}°`,`${a/2}°`,`${a}°`,`${a*2}°`],1,`同弧所对圆周角等于圆心角的一半，所以答案是 ${a/2}°。`,`The inscribed angle is half the central angle, so the answer is ${a/2}°.`));
[15,20,25,30,35,40,45,50,55,60,65,70].forEach((a,i)=>t("topic-ic-"+String(i+1).padStart(3,"0"),"topic","圆心角与圆周角","Central and Inscribed Angles",3+i%2,3,`若某圆周角为 ${a}°，则对应圆心角是（ ）`,`If an inscribed angle is ${a}°, the corresponding central angle is?`,[`${a}°`,`${a*2}°`,`${a+30}°`,`${a*3}°`],[`${a}°`,`${a*2}°`,`${a+30}°`,`${a*3}°`],1,`对应圆心角等于圆周角的两倍，所以答案是 ${a*2}°。`,`The central angle is twice the inscribed angle, so the answer is ${a*2}°.`));
["半径与切线在切点处（ ）","若直线是圆的切线，则它与过切点的半径（ ）","切线与圆在切点处和半径的位置关系是（ ）","圆的切线与切点处半径总是（ ）","判断直线是圆的切线时，常利用它与半径（ ）"].forEach((s,i)=>{for(let k=0;k<2;k++)t("topic-tg-"+String(i*2+k+1).padStart(3,"0"),"topic","切线性质","Tangent Properties",3+k,2+k,s,"Which relation is true for a tangent and radius at the tangency point?",["平行","重合","垂直","没有关系"],["Parallel","Coincident","Perpendicular","Unrelated"],2,"切线与经过切点的半径垂直。","A tangent is perpendicular to the radius through the point of tangency.")});
[["较短",0],["较长",1],["更长",1],["更靠近圆心",1],["更靠内侧",1],["更接近中心",1],["位置更靠中部",1],["明显更短",0],["略短",0],["更靠圆外",0]].forEach((x,i)=>t("topic-ch-"+String(i+1).padStart(3,"0"),"topic","弦与弧","Chords and Arcs",4,2+i%3,`在同圆中，若弦 AB 比弦 CD ${x[0]}，则通常有（ ）`,`In the same circle, if chord AB is ${x[0]} than chord CD, then usually?`,["弧 AB 更短","弧 AB 更长","弧 AB = 弧 CD","无法判断"],["Arc AB is shorter","Arc AB is longer","Arc AB equals arc CD","Cannot be determined"],x[1],x[1]===0?"若弦较短，则对应弧通常也较短。":"若弦较长，则对应弧通常也较长。",x[1]===0?"A shorter chord usually corresponds to a shorter arc.":"A longer chord usually corresponds to a longer arc."));
["同圆中，相等的弦所对的弧（ ）","在同圆中，若两条弦相等，则对应两段弧（ ）","同一个圆内，等弦对应的弧（ ）","相等弦在同圆中对应的弧（ ）","若两条弦属于同圆且长度相等，则它们所对的弧（ ）","同圆中，长度相等的弦对应的弧（ ）","在同圆里，相等的弦会对应（ ）","若弦 AB = 弦 CD，且它们属于同圆，则弧 AB 与弧 CD（ ）"].forEach((s,i)=>t("topic-eq-"+String(i+1).padStart(3,"0"),"topic","弦与弧","Chords and Arcs",3+i%2,3,s,"Equal chords in the same circle correspond to arcs that are?",["相等","互补","平行","垂直"],["Equal","Supplementary","Parallel","Perpendicular"],0,"同圆中，相等的弦所对的弧相等。","In the same circle, equal chords subtend equal arcs."));

[5,6,7,8,9,10,11,12,13,14,15,16,18,20,22,24].forEach((r,i)=>c("comp-rd-"+String(i+1).padStart(3,"0"),2+i%3,3+i%2,`某圆的半径是 ${r} cm，直径是（ ）`,`A circle has radius ${r} cm. The diameter is?`,[`${r-1} cm`,`${r*2} cm`,`${r*3} cm`,`${r} cm`],[`${r-1} cm`,`${r*2} cm`,`${r*3} cm`,`${r} cm`],1,`直径等于半径的两倍，所以应选 ${r*2} cm。`,`The diameter is twice the radius, so the answer is ${r*2} cm.`));
[30,40,50,60,70,80,90,100,110,120,130,140,150,160,170,180].forEach((a,i)=>c("comp-ca-"+String(i+1).padStart(3,"0"),3+i%3,2+i%3,`若圆心角为 ${a}°，则同弧所对圆周角是（ ）`,`If the central angle is ${a}°, the inscribed angle on the same arc is?`,[`${a/2}°`,`${a}°`,`${a/3}°`,`${a*2}°`],[`${a/2}°`,`${a}°`,`${a/3}°`,`${a*2}°`],0,`圆周角等于对应圆心角的一半，所以答案是 ${a/2}°。`,`The inscribed angle is half the corresponding central angle, so the answer is ${a/2}°.`));
[15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,60].forEach((a,i)=>c("comp-ia-"+String(i+1).padStart(3,"0"),3+i%2,3,`若圆周角是 ${a}°，则对应圆心角为（ ）`,`If the inscribed angle is ${a}°, the corresponding central angle is?`,[`${a}°`,`${a*2}°`,`${a+20}°`,`${a*3}°`],[`${a}°`,`${a*2}°`,`${a+20}°`,`${a*3}°`],1,`对应圆心角是圆周角的两倍，所以答案是 ${a*2}°。`,`The corresponding central angle is twice the inscribed angle, so the answer is ${a*2}°.`));
[1,2,3,4,5,6,7,8].forEach(n=>{c("comp-tg-"+String(n).padStart(3,"0"),4,2+n%3,`从圆外一点 P 引圆的两条切线段 PA、PB，则下列结论正确的是（ ）第 ${n} 题`,`From an external point P, PA and PB are tangent segments. Which is correct? Question ${n}`,["PA = PB","PA > PB","PA < PB","无法比较"],["PA = PB","PA > PB","PA < PB","Cannot compare"],0,"同一点向圆引出的两条切线段长度相等。","Two tangent segments from the same external point are equal.");c("comp-tp-"+String(n).padStart(3,"0"),4,3,`若半径 OA 与直线 l 在点 A 处垂直，且 A 在圆上，则直线 l 是（ ）第 ${n} 题`,`If radius OA is perpendicular to line l at point A on the circle, then l is? Question ${n}`,["弦","割线","切线","直径"],["Chord","Secant","Tangent","Diameter"],2,"经过圆上某点且垂直于该点半径的直线是切线。","A line perpendicular to the radius at a point on the circle is tangent.")});
[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16].forEach((n,i)=>c("comp-ch-"+String(i+1).padStart(3,"0"),5,2,`同圆中，若弦 AB 到圆心的距离大于弦 CD 到圆心的距离，则（ ）第 ${n} 题`,`In the same circle, if chord AB is farther from the center than chord CD, then? Question ${n}`,["AB 更长","AB 更短","AB = CD","无法判断"],["AB is longer","AB is shorter","AB = CD","Cannot be determined"],1,"同圆中，离圆心越远的弦越短。","In the same circle, the chord farther from the center is shorter."));

[
["daily-001","圆基础","Circle Basics","基础","Basic",2,3,"今日精选 1：圆中最长的弦是（ ）","Daily Pick 1: The longest chord in a circle is?",["半径","直径","切线","弧"],["Radius","Diameter","Tangent","Arc"],1,"直径是圆中最长的弦。","The diameter is the longest chord in a circle."],
["daily-002","圆基础","Circle Basics","基础","Basic",2,4,"今日精选 2：半径为 9 cm 的圆，其直径为（ ）","Daily Pick 2: A circle of radius 9 cm has diameter?",["9 cm","18 cm","27 cm","36 cm"],["9 cm","18 cm","27 cm","36 cm"],1,"直径等于半径的两倍。","The diameter is twice the radius."],
["daily-003","圆周角","Inscribed Angle","进阶","Intermediate",3,3,"今日精选 3：若圆心角为 120°，同弧所对圆周角是（ ）","Daily Pick 3: If the central angle is 120°, the inscribed angle is?",["30°","60°","120°","240°"],["30°","60°","120°","240°"],1,"圆周角等于圆心角的一半。","The inscribed angle is half the central angle."],
["daily-004","切线性质","Tangent Property","进阶","Intermediate",3,3,"今日精选 4：半径与切线在切点处（ ）","Daily Pick 4: At the tangency point, a radius and tangent are?",["平行","垂直","重合","相等"],["Parallel","Perpendicular","Coincident","Equal"],1,"半径与切线在切点处垂直。","A radius is perpendicular to a tangent at the point of tangency."],
["daily-005","弦与弧","Chords and Arcs","提高","Advanced",4,2,"今日精选 5：同圆中，相等的弦所对的弧（ ）","Daily Pick 5: In the same circle, equal chords subtend arcs that are?",["相等","垂直","互补","无法判断"],["Equal","Perpendicular","Supplementary","Cannot be determined"],0,"相等的弦所对弧相等。","Equal chords subtend equal arcs."],
["daily-006","圆基础","Circle Basics","基础","Basic",2,4,"今日精选 6：连接圆上两点的线段叫做（ ）","Daily Pick 6: A segment joining two points on the circle is a?",["半径","弦","切线","直径"],["Radius","Chord","Tangent","Diameter"],1,"连接圆上两点的线段叫做弦。","A segment joining two points on the circle is a chord."],
["daily-007","圆周角","Inscribed Angle","进阶","Intermediate",3,3,"今日精选 7：直径所对的圆周角是（ ）","Daily Pick 7: The inscribed angle subtending a diameter is?",["锐角","直角","钝角","平角"],["Acute","Right","Obtuse","Straight"],1,"直径所对圆周角恒为直角。","An inscribed angle subtending a diameter is always right."],
["daily-008","切线性质","Tangent Property","提高","Advanced",4,2,"今日精选 8：从圆外一点引圆的两条切线段（ ）","Daily Pick 8: Two tangent segments from the same external point are?",["相等","不等","互补","平行"],["Equal","Unequal","Supplementary","Parallel"],0,"同一点引出的两条切线段长度相等。","Two tangent segments from the same point are equal."],
["daily-009","弦与弧","Chords and Arcs","提高","Advanced",4,2,"今日精选 9：离圆心越近的弦通常（ ）","Daily Pick 9: A chord closer to the center is usually?",["越短","越长","不变","一定是直径"],["Shorter","Longer","Unchanged","Always a diameter"],1,"离圆心越近的弦越长。","A chord nearer the center is longer."],
["daily-010","圆基础","Circle Basics","基础","Basic",2,4,"今日精选 10：若圆的直径为 18 cm，则半径为（ ）","Daily Pick 10: If the diameter is 18 cm, the radius is?",["6 cm","9 cm","18 cm","36 cm"],["6 cm","9 cm","18 cm","36 cm"],1,"半径等于直径的一半。","The radius is half the diameter."],
["daily-011","圆周角","Inscribed Angle","进阶","Intermediate",3,3,"今日精选 11：若圆周角为 35°，则对应圆心角为（ ）","Daily Pick 11: If the inscribed angle is 35°, the central angle is?",["35°","70°","105°","140°"],["35°","70°","105°","140°"],1,"圆心角是圆周角的两倍。","The central angle is twice the inscribed angle."],
["daily-012","切线性质","Tangent Property","提高","Advanced",4,2,"今日精选 12：若直线与圆上某点的半径垂直，则该直线是（ ）","Daily Pick 12: If a line is perpendicular to a radius at a point on the circle, it is?",["弦","切线","割线","直径"],["Chord","Tangent","Secant","Diameter"],1,"满足该条件时直线为切线。","Under that condition, the line is tangent."],
["daily-013","弦与弧","Chords and Arcs","进阶","Intermediate",3,3,"今日精选 13：同圆中，相等的弧所对的弦（ ）","Daily Pick 13: In the same circle, equal arcs correspond to chords that are?",["相等","平行","垂直","互补"],["Equal","Parallel","Perpendicular","Supplementary"],0,"相等弧对应相等弦。","Equal arcs correspond to equal chords."],
["daily-014","圆基础","Circle Basics","基础","Basic",2,4,"今日精选 14：圆中最长的弦与圆心的关系是（ ）","Daily Pick 14: The longest chord in a circle?",["经过圆心","与圆心无关","垂直于半径","在圆外"],["Passes through the center","No relation","Perpendicular to a radius","Outside the circle"],0,"最长弦就是直径，必经过圆心。","The longest chord is the diameter, so it passes through the center."],
["daily-015","圆周角","Inscribed Angle","进阶","Intermediate",3,3,"今日精选 15：若圆心角为 90°，对应圆周角是（ ）","Daily Pick 15: If the central angle is 90°, the inscribed angle is?",["30°","45°","90°","180°"],["30°","45°","90°","180°"],1,"圆周角等于圆心角的一半。","The inscribed angle is half the central angle."],
["daily-016","切线性质","Tangent Property","提高","Advanced",4,2,"今日精选 16：圆的切线与圆有（ ）个公共点","Daily Pick 16: A tangent and a circle have how many common points?",["0","1","2","无数"],["0","1","2","Infinite"],1,"切线与圆只有一个公共点。","A tangent has exactly one common point with the circle."],
["daily-017","弦与弧","Chords and Arcs","提高","Advanced",4,2,"今日精选 17：同圆中，较长的弦对应的弧通常（ ）","Daily Pick 17: In the same circle, a longer chord usually corresponds to an arc that is?",["更短","更长","相等","不变"],["Shorter","Longer","Equal","Unchanged"],1,"较长的弦通常对应较长的弧。","A longer chord usually corresponds to a longer arc."],
["daily-018","圆基础","Circle Basics","基础","Basic",2,4,"今日精选 18：半径为 12 cm 的圆，其直径是（ ）","Daily Pick 18: A circle with radius 12 cm has diameter?",["6 cm","12 cm","24 cm","36 cm"],["6 cm","12 cm","24 cm","36 cm"],2,"直径等于半径的两倍。","The diameter equals twice the radius."],
["daily-019","圆周角","Inscribed Angle","进阶","Intermediate",3,3,"今日精选 19：同弧所对的两个圆周角（ ）","Daily Pick 19: Two inscribed angles subtending the same arc are?",["相等","互补","垂直","无法判断"],["Equal","Supplementary","Perpendicular","Cannot be determined"],0,"同弧所对圆周角相等。","Inscribed angles subtending the same arc are equal."],
["daily-020","切线性质","Tangent Property","提高","Advanced",4,2,"今日精选 20：从圆外一点引圆的两条切线段长度（ ）","Daily Pick 20: Two tangent segments from the same external point are?",["相等","不等","一长一短","无法判断"],["Equal","Unequal","One longer, one shorter","Cannot be determined"],0,"两条切线段长度相等。","Two tangent segments from the same external point are equal."],
["daily-021","弦与弧","Chords and Arcs","进阶","Intermediate",3,3,"今日精选 21：同圆中，相等的弦所对的弧（ ）","Daily Pick 21: In the same circle, equal chords subtend arcs that are?",["相等","互补","平行","垂直"],["Equal","Supplementary","Parallel","Perpendicular"],0,"相等弦所对弧相等。","Equal chords subtend equal arcs."],
["daily-022","圆基础","Circle Basics","基础","Basic",2,4,"今日精选 22：若某圆的直径为 30 cm，则半径为（ ）","Daily Pick 22: If the diameter is 30 cm, the radius is?",["10 cm","15 cm","30 cm","60 cm"],["10 cm","15 cm","30 cm","60 cm"],1,"半径等于直径的一半。","The radius is half the diameter."],
["daily-023","圆周角","Inscribed Angle","进阶","Intermediate",3,3,"今日精选 23：若圆周角为 50°，对应圆心角是（ ）","Daily Pick 23: If the inscribed angle is 50°, the central angle is?",["25°","50°","100°","150°"],["25°","50°","100°","150°"],2,"圆心角是圆周角的两倍。","The central angle is twice the inscribed angle."],
["daily-024","切线性质","Tangent Property","提高","Advanced",4,2,"今日精选 24：判断一条直线是圆的切线，常用条件是它与半径（ ）","Daily Pick 24: To prove a line is tangent, a common condition is that it is what to a radius?",["平行","重合","垂直","相等"],["Parallel","Coincident","Perpendicular","Equal"],2,"与半径在圆上一点垂直可判定切线。","Being perpendicular to a radius at a point on the circle proves tangency."],
["daily-025","弦与弧","Chords and Arcs","提高","Advanced",4,2,"今日精选 25：若弦离圆心越近，则该弦通常（ ）","Daily Pick 25: The closer a chord is to the center, it is usually?",["越短","越长","不变","一定是直径"],["Shorter","Longer","Unchanged","Always a diameter"],1,"同圆中，离圆心越近的弦越长。","In the same circle, a chord nearer the center is longer."],
["daily-026","圆基础","Circle Basics","基础","Basic",2,4,"今日精选 26：连接圆上两点的线段一定不是（ ）","Daily Pick 26: A segment joining two points on the circle is definitely not a?",["弦","直径","半径","可能是直径"],["Chord","Diameter","Radius","Possibly a diameter"],2,"连接圆上两点的线段是弦，不是半径。","A segment joining two points on the circle is a chord, not a radius."],
["daily-027","圆周角","Inscribed Angle","进阶","Intermediate",3,3,"今日精选 27：若圆心角为 150°，则对应圆周角为（ ）","Daily Pick 27: If the central angle is 150°, the inscribed angle is?",["60°","75°","90°","150°"],["60°","75°","90°","150°"],1,"圆周角等于圆心角的一半。","The inscribed angle is half the central angle."],
["daily-028","切线性质","Tangent Property","提高","Advanced",4,2,"今日精选 28：切线与圆的位置关系是（ ）","Daily Pick 28: What is the position relation between a tangent and a circle?",["有两个公共点","有一个公共点","没有公共点","有无数公共点"],["Two common points","One common point","No common points","Infinitely many common points"],1,"切线与圆只有一个公共点。","A tangent and a circle have exactly one common point."],
["daily-029","弦与弧","Chords and Arcs","进阶","Intermediate",3,3,"今日精选 29：同圆中，相等的弧对应的弦（ ）","Daily Pick 29: In the same circle, equal arcs correspond to chords that are?",["相等","互补","垂直","平行"],["Equal","Supplementary","Perpendicular","Parallel"],0,"同圆中，相等弧对应相等弦。","Equal arcs correspond to equal chords in the same circle."],
["daily-030","圆基础","Circle Basics","基础","Basic",2,4,"今日精选 30：若圆半径为 3.5 cm，则直径是（ ）","Daily Pick 30: If the radius is 3.5 cm, the diameter is?",["3.5 cm","7 cm","10.5 cm","14 cm"],["3.5 cm","7 cm","10.5 cm","14 cm"],1,"直径等于半径的两倍，所以是 7 cm。","The diameter is twice the radius, so it is 7 cm."],
["daily-031","圆周角","Inscribed Angle","进阶","Intermediate",3,3,"今日精选 31：同弧所对圆周角与圆心角的关系是（ ）","Daily Pick 31: The inscribed angle and central angle for the same arc are?",["相等","两倍","一半","不相关"],["Equal","Twice","Half","Unrelated"],2,"圆周角等于同弧所对圆心角的一半。","The inscribed angle is half the central angle of the same arc."],
["daily-032","切线性质","Tangent Property","提高","Advanced",4,2,"今日精选 32：若 PA、PB 是同一点引圆的切线段，则（ ）","Daily Pick 32: If PA and PB are tangent segments from the same point, then?",["PA = PB","PA > PB","PA < PB","无法判断"],["PA = PB","PA > PB","PA < PB","Cannot be determined"],0,"同一点引出的两条切线段长度相等。","Two tangent segments from the same point are equal."],
["daily-033","弦与弧","Chords and Arcs","提高","Advanced",4,2,"今日精选 33：在同圆中，弧越长，则对应弦通常（ ）","Daily Pick 33: In the same circle, the longer the arc, the corresponding chord is usually?",["越短","越长","不变","无法判断"],["Shorter","Longer","Unchanged","Cannot be determined"],1,"较长弧通常对应较长弦。","A longer arc usually corresponds to a longer chord."],
["daily-034","圆基础","Circle Basics","基础","Basic",2,4,"今日精选 34：若直径为 40 cm，则半径为（ ）","Daily Pick 34: If the diameter is 40 cm, the radius is?",["10 cm","20 cm","40 cm","80 cm"],["10 cm","20 cm","40 cm","80 cm"],1,"半径等于直径的一半。","The radius is half the diameter."],
["daily-035","圆周角","Inscribed Angle","进阶","Intermediate",3,3,"今日精选 35：若某圆周角为 65°，对应圆心角为（ ）","Daily Pick 35: If an inscribed angle is 65°, the central angle is?",["65°","110°","130°","195°"],["65°","110°","130°","195°"],2,"对应圆心角等于圆周角的两倍。","The central angle is twice the inscribed angle."],
["daily-036","切线性质","Tangent Property","提高","Advanced",4,2,"今日精选 36：经过切点且垂直于半径的直线是（ ）","Daily Pick 36: A line through the tangency point and perpendicular to the radius is?",["弦","切线","割线","直径"],["Chord","Tangent","Secant","Diameter"],1,"满足该条件的直线是切线。","A line satisfying this condition is tangent."],
["daily-037","弦与弧","Chords and Arcs","进阶","Intermediate",3,3,"今日精选 37：同圆中，相等的弦与对应弧的关系是（ ）","Daily Pick 37: In the same circle, equal chords and their corresponding arcs are?",["都相等","都互补","都垂直","无法判断"],["Both equal","Both supplementary","Both perpendicular","Cannot be determined"],0,"相等弦对应相等弧。","Equal chords correspond to equal arcs."],
["daily-038","圆基础","Circle Basics","基础","Basic",2,4,"今日精选 38：圆中最长弦一定（ ）","Daily Pick 38: The longest chord in a circle must?",["经过圆心","平行于半径","在圆外","与圆心无关"],["Pass through the center","Be parallel to a radius","Be outside the circle","Have no relation to the center"],0,"最长弦是直径，必经过圆心。","The longest chord is the diameter, so it passes through the center."],
["daily-039","圆周角","Inscribed Angle","进阶","Intermediate",3,3,"今日精选 39：若圆心角为 70°，同弧所对圆周角为（ ）","Daily Pick 39: If the central angle is 70°, the inscribed angle is?",["35°","70°","105°","140°"],["35°","70°","105°","140°"],0,"圆周角是圆心角的一半。","The inscribed angle is half the central angle."],
["daily-040","切线性质","Tangent Property","提高","Advanced",4,2,"今日精选 40：切线与圆的公共点叫做（ ）","Daily Pick 40: The common point of a tangent and a circle is called?",["圆心","切点","弦心","圆周角"],["Center","Point of tangency","Chord center","Inscribed angle"],1,"切线与圆唯一公共点叫切点。","The unique common point of a tangent and a circle is the point of tangency."]
].forEach(x=>d.apply(null,x));
const all=topic.concat(comprehensive).concat(daily);const by=s=>all.filter(q=>q.source===s);return{all:all,topic:by("topic"),comprehensive:by("comprehensive"),daily:by("daily")}})();
